### ISSUE TITLE
error messages from ApplicationwithTBdataset tutorial 

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netbooks#19]
ApplicationwithTBdataset
	-error thrown back for chunks 7 and 8
	-analysis still ran though 
￼
<img width="1095" alt="Screenshot 2023-09-28 at 12 50 14 PM" src="https://github.com/netZoo/netbooks/assets/145356744/3d66eca0-ff23-4b4c-b1d9-e2567af388e8">

<img width="1084" alt="Screenshot 2023-09-28 at 12 50 27 PM" src="https://github.com/netZoo/netbooks/assets/145356744/9505a774-2862-4487-b42e-f9d8f305884d">

<img width="968" alt="Screenshot 2023-09-28 at 2 43 28 PM" src="https://github.com/netZoo/netbooks/assets/145356744/60b65f33-f390-43f3-9761-53021975c4c6">

<img width="924" alt="Screenshot 2023-09-28 at 2 52 43 PM" src="https://github.com/netZoo/netbooks/assets/145356744/703f5180-e641-4c34-9c47-e19b5cfc2fd9">

￼
￼
￼

**Comment by marouenbg** [comment]
@wilsonavac  ApplicationwithTBdataset.ipynb doesn't have a chunk 7 on Netbooks, where did you get the tutorial file?

**Comment by wilsonavac** [comment]
http://netbooks.networkmedicine.org/user/wilsonavac/notebooks/netZooR/ApplicationwithTBdataset.ipynb

This is the link that I used,

**Comment by marouenbg** [comment]
Fixed in https://github.com/netZoo/netbooks/commit/5374f2e64f30a0dfc4039d3e43738035b536b650 Thank you @wilsonavac !
