### ISSUE TITLE
Running COBRA tutorial in R

### ISSUE THREAD

**Issue by soelmicheletti** [netZoo/netbooks#21]
Currently, two packages required for the cobra tutorial in R are not installed

- recount3 (to download TCGA data)
- fastDummies (for dummy coding of categorical variables)

If we prefer, we can upload a dataset and avoid installing recount3 in the server. 

Additionately, COBRA is currently in the devel branch of netZooR. I think this is the reason why we can't run cobra on the server yet.

**Comment by marouenbg** [comment]
solved in https://github.com/netZoo/netbooks/commit/9ff49653bcd9244f865ee148cf190b9b2ce9c914
