### ISSUE TITLE
SEAHORSE Netbooks: Syntax error

### ISSUE THREAD

**Issue by Enakshi-Saha** [netZoo/netbooks#28]
@marouenbg in the Netbook titled "Uncovering Associations among Genes and Phenotypes with SEAHORSE", the second cell gives a syntax error.
<img width="546" alt="Screenshot 2024-04-19 at 1 29 17 PM" src="https://github.com/netZoo/netbooks/assets/66750297/b9b0aec6-6bc2-4082-89ed-44d4c3a8b3e2">

**Comment by marouenbg** [comment]
It is working now can you check again @Enakshi-Saha ?
