### ISSUE TITLE
unable to install/load visNetwork dependency for panda_gtex_tutorial_server.ipynb netbook 

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netbooks#30]
`install.packages("visNetwork")`

Warning message in install.packages("visNetwork"):
“'lib = "/opt/conda/envs/rc4/lib/R/library"' is not writable”
Error in install.packages("visNetwork"): unable to install packages
Traceback:

1. install.packages("visNetwork")
2. stop("unable to install packages")

**Comment by marouenbg** [comment]
duplicate in https://github.com/netZoo/netbooks/issues/29
