### ISSUE TITLE
Error received for chunk 28 code in panda_gtex_tutorial_server.ipynb

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netbooks#31]
`lcl_outdegree <- calcDegree(pandaLCL, type="tf")
wb_outdegree <- calcDegree(pandaWB, type="tf")`

Error in calcDegree(pandaLCL, type = "tf"): Cannot run calcDegree on object of class 'pandaObj'.  Must be of class 'panda' or 'matrix'.
Traceback:

1. calcDegree(pandaLCL, type = "tf")
2. stop(paste(sep = "", "Cannot run calcDegree on object of class '", 
 .     class(x), "'.  Must be of class 'panda' or 'matrix'."))

**Comment by marouenbg** [comment]
This was fixed now, try again @wilsonavac
