### ISSUE TITLE
package gprofiler2 missing from condor-netbook.ipynb RP2

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netbooks#32]
Error in library(gprofiler2): there is no package called ‘gprofiler2’
Traceback:

1. library(gprofiler2)

**Comment by marouenbg** [comment]
Fixed in https://github.com/netZoo/netbooks/commit/b7b8ea3d0f32f899b6624ffddac91d9236ae9109
@wilsonavac can you have a look one more time?

**Comment by marouenbg** [comment]
@wilsonavac Is this working now?
