### ISSUE TITLE
error message received for chunks 28-30 in panda_gtex_tutorial_server.ipynb

### ISSUE THREAD

**Issue by wilsonavac** [netZoo/netbooks#33]
Error in calcDegree(pandaLCL, type = "tf"): Cannot run calcDegree on object of class 'pandaObj'.  Must be of class 'panda' or 'matrix'.
Traceback:

1. calcDegree(pandaLCL, type = "tf")
2. stop(paste(sep = "", "Cannot run calcDegree on object of class '", 
 .     class(x), "'.  Must be of class 'panda' or 'matrix'."))

**Comment by marouenbg** [comment]
@wilsonavac , is this the same as https://github.com/netZoo/netbooks/issues/31 ?
