### ISSUE TITLE
CONDOR tutorial with netZooPy 0.9.6

### ISSUE THREAD

**Issue by marouenbg** [netZoo/netbooks#4]
Hi @genisott

I am transcribing my issue here otherwise I will forget :)
So updating netZooPy 0.9.6 with new condor code, the condor tutorial fails
https://github.com/netZoo/netbooks/blob/main/netbooks/netZooPy/condor_tutorial.ipynb

Please let me know if you have any clue !

**Comment by genisott** [comment]
Hi @marouenbg,
It looks like the version of the tutorial notebook in netbooks is even using the previous version of condor (the one from several years ago). The proper tutorial notebook is in the netZooPy/tutorials and I just checked that it works with the new version.

**Comment by marouenbg** [comment]
Hi @genisott ,
I am having a little issue with my computer and I am waiting for a replacement, I will look at the issue again in a few days.
Marouen

**Comment by marouenbg** [comment]
Hi @genisott ,
Turns out igraph has to be >0.9.6 for the tutorial to work, great job on condor by the way, I love the new API! :)
