### ISSUE TITLE
Error in h(simpleError(msg, call))

### ISSUE THREAD

**Issue by lemonsky123** [netZoo/netbooks#7]
Hi, when I was running the notebook "Differential gene targeting of pancreatic cancer subtypes", I got the following error: Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'mcols': Failed to find a rowRanges() method for RangedSummarizedExperiment objects.  The screenshot is listed below.

![P2{Q5JXAHZSG0Y0AMA}E4K](https://user-images.githubusercontent.com/50455057/186827743-bde376d0-7ba9-48eb-9e40-05a148cb5f6c.png)

Would you please help me with this problem? Thanks very much!

**Comment by marouenbg** [comment]
Hi @lemonsky123 ,

I am sorry this took so long, for some reason, I didn't get a notification about this issue.
So this has been solved now, the SummarizedExperiment package had to be reinstalled.

Thank you,
Marouen

**Comment by lemonsky123** [comment]
> Hi @lemonsky123 ,
> 
> I am sorry this took so long, for some reason, I didn't get a notification about this issue. So this has been solved now, the SummarizedExperiment package had to be reinstalled.
> 
> Thank you, Marouen

Hi Marouen @marouenbg 

Thanks for the reply. I found another two problems when I was running the notebook "Building PANDA and LIONESS Regulatory Networks from GTEx Gene Expression Data in R". The problems are listed below.

1) I ran the notebook on your jupyterhub server two times, and I got two different panda scores for the same edges.
    **_The screenshot for the first run is listed below_**
    
![WPS图片(1)](https://user-images.githubusercontent.com/50455057/192150135-38f2f339-19a8-406b-b44d-a0a6859e98b1.png)
    **_The screenshot for the ssecond run is listed below_**

![WPS图片(1)](https://user-images.githubusercontent.com/50455057/192150247-5e5630c2-791b-4614-993b-fb20fbee926d.png)
    As you can see, there are slight differences between the panda scores of the same edges. Why does this difference exists? 

2) I installed netzooR on my local jupyter server according to your tutorial and I downloaded the example dataset from "Building PANDA and LIONESS Regulatory Networks from GTEx Gene Expression Data in R". I ran the same data with the same codes to your tutorial and I got a **_totally different panda scores_** from yours.

    The first screenshot below is the results on your jupyterhub server
![WPS图片(1)](https://user-images.githubusercontent.com/50455057/192150856-9da1dd26-c2b7-48e6-a530-568c467f2bb0.png)
    
    The second screenshot below is the results on my local jupyter notebook.
![WPS图片(1)](https://user-images.githubusercontent.com/50455057/192150968-1a900535-01ff-4149-a859-d61c69c5afb1.png)

    As you can see, the panda scores of my jupyter server are quite different from those on your jupyterhub. I checked the versions of R and netzooR on my local jupyter environment, and they are same as yours. What would be the reason for this dirrerence? would you please help me? Thanks very much!

**Comment by marouenbg** [comment]
Hi @lemonsky123 ,

Thank you for letting me know about this! For the first question, how can I reproduce the inconsistency between PANDA results on the server? What did you do to get the first and second runs?

Thank you,
Marouen

**Comment by lemonsky123** [comment]
> Hi @lemonsky123 ,
> 
> Thank you for letting me know about this! For the first question, how can I reproduce the inconsistency between PANDA results on the server? What did you do to get the first and second runs?
> 
> Thank you, Marouen

Hi Marouen @marouenbg 

For the first question, I simply ran the notebook on your jupyterhub server twice. Each time I ran the notebook, I got different panda scores. Would you please run the notebook "Building PANDA and LIONESS Regulatory Networks from GTEx Gene Expression Data in R" twice or third times? Let's see whether you could get different panda scores each time you run the notebook. Thanks very much!

**Comment by lemonsky123** [comment]
> Hi @lemonsky123 ,
> 
> Thank you for letting me know about this! For the first question, how can I reproduce the inconsistency between PANDA results on the server? What did you do to get the first and second runs?
> 
> Thank you, Marouen

Hi Marouen @marouenbg 

Sorry to bother you, do you have any update on these two questions?

Thank you.

**Comment by marouenbg** [comment]
Hi @lemonsky123 ,

Yes I confirm this issue, I had the same results both on server and local as you did. I am looking at this now.

**Comment by marouenbg** [comment]
Hi @lemonsky123 ,

So this was fixed, thanks for reporting it. The function pandaPy is a python function that we call from R through reticulate because it is faster than panda() pure R function. However, the reticulate package seems to be unstable when python is hard coded as opposed to automatically detected by the system.

If there is anything else, please feel free to open a new issue.
