### ISSUE TITLE
Not able to find file paths in some notebooks

### ISSUE THREAD

**Issue by alejokeuro** [netZoo/netbooks#8]
Hi @marouenbg ,

I'm not beeing able to find the file paths pointing to auxiliary data to run some of the notebooks. These file paths are supposed to point to an S3 bucket. Some of the notebooks have the file paths, but others don't. E.g., the notebook about building a seed regulatory network ( [https://github.com/netZoo/netbooks/blob/main/netbooks/netZooPy/Building_a_regulation_prior_network.ipynb](https://github.com/netZoo/netbooks/blob/main/netbooks/netZooPy/Building_a_regulation_prior_network.ipynb) ) doesn't show the actual file paths in an S3 bucket. Other notebooks do show it; e.g., this one: [https://github.com/netZoo/netbooks/blob/main/netbooks/netZooPy/Controlling_The_Variance_Of_PANDA_Networks.ipynb](https://github.com/netZoo/netbooks/blob/main/netbooks/netZooPy/Controlling_The_Variance_Of_PANDA_Networks.ipynb). Am I looking in the right place?

It looks like the data is pre-loaded on jupyter-hub when I run the notebooks there. I mean, when I run the notebooks at [http://netbooks.networkmedicine.org/](http://netbooks.networkmedicine.org/). Still, I would like to run the notebooks locally, so I don't have to worry about the session expiring, and I can explore the data files outside a jupyter notebook.

Any help on this would be very much appreciated. Thank you in advance!

**Comment by marouenbg** [comment]
Hey @alejokeuro ,

Thank you for reporting this, I added the required data in the notebook you mentioned. Please let me know if you have any other questions!

Marouen

**Comment by alejokeuro** [comment]
Hi @marouenbg ,

thank you very much for your help! I managed to download the auxiliary data from the paths you added.

Cheers!

Alejo
